import { Pool } from "pg";
let pool: Pool | null = null;
function gp() { if (!process.env.DATABASE_URL) return null; if (!pool) pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }); return pool; }

export type Landing = { slug: string; h1: string; title: string; intro: string; where: string };

// All `where` clauses are hardcoded here (never user input) -> safe to interpolate.
export const LANDINGS: Landing[] = [
  { slug: "happy-hours-las-vegas-strip", h1: "Best Happy Hours on the Las Vegas Strip", title: "Best Happy Hours on the Las Vegas Strip (Updated Weekly)", intro: "Verified happy hour deals at bars and restaurants on and just off the Strip — with real prices, times, and when each was last confirmed.", where: "sp.category='happy_hour' AND v.neighborhood ILIKE '%Strip%'" },
  { slug: "happy-hours-downtown-las-vegas", h1: "Best Happy Hours in Downtown Las Vegas", title: "Best Happy Hours in Downtown Las Vegas & Fremont", intro: "The freshest happy hour deals in Downtown Las Vegas and the Fremont East district.", where: "sp.category='happy_hour' AND v.neighborhood ILIKE '%Downtown%'" },
  { slug: "happy-hours-arts-district-las-vegas", h1: "Best Happy Hours in the Las Vegas Arts District", title: "Happy Hours in the Las Vegas Arts District (18b)", intro: "Where locals drink — verified happy hours across the Arts District.", where: "sp.category='happy_hour' AND v.neighborhood ILIKE '%Arts%'" },
  { slug: "cheap-drinks-las-vegas", h1: "Cheap Drink Specials in Las Vegas ($6 & Under)", title: "Cheap Drinks in Las Vegas — $6 & Under Specials", intro: "Every verified drink special $6 or less, citywide. Updated automatically as our crawler and locals find new deals.", where: "sp.drink AND sp.price IS NOT NULL AND sp.price <= 6" },
  { slug: "meals-under-10-las-vegas", h1: "Meals & Food Specials Under $10 in Las Vegas", title: "Cheap Eats: Meals Under $10 in Las Vegas", intro: "Real food deals for under ten bucks — steak specials, bites, and more, verified and dated.", where: "sp.food AND sp.price IS NOT NULL AND sp.price <= 10" },
  { slug: "2-for-1-drink-specials-las-vegas", h1: "2-for-1 & BOGO Drink Specials in Las Vegas", title: "2-for-1 Drink Specials in Las Vegas", intro: "Buy-one-get-one and two-for-one drink deals across Las Vegas.", where: "sp.drink AND sp.discount_type IN ('two_for_one','bogo')" },
  { slug: "free-drinks-and-freebies-las-vegas", h1: "Free Drinks & Freebies in Las Vegas", title: "Free Drinks & Freebies in Las Vegas", intro: "Free beers for veterans, players-card perks, comps and other freebies — verified.", where: "sp.freebie" },
  { slug: "late-night-happy-hours-las-vegas", h1: "Late-Night & Reverse Happy Hours in Las Vegas", title: "Late-Night Happy Hours in Las Vegas (After 10pm)", intro: "Vegas runs all night. These spots run a second, later discount window.", where: "sp.reverse_window IS NOT NULL AND sp.reverse_window <> ''" },
  { slug: "sushi-happy-hours-las-vegas", h1: "Sushi Happy Hours in Las Vegas", title: "Best Sushi Happy Hours in Las Vegas", intro: "Discounted rolls, sake and nigiri across Las Vegas sushi bars — verified and dated.", where: "(v.cuisine ILIKE '%sush%' OR v.cuisine ILIKE '%japanese%' OR sp.summary ILIKE '%sushi%' OR sp.summary ILIKE '%roll%' OR sp.summary ILIKE '%nigiri%')" },
  { slug: "oyster-happy-hours-las-vegas", h1: "Oyster Happy Hours in Las Vegas", title: "Best Oyster Happy Hours & $1 Oyster Deals in Las Vegas", intro: "Where to find cheap oysters in Las Vegas right now — dollar oysters, oyster happy hours and seafood specials.", where: "sp.summary ILIKE '%oyster%'" },
  { slug: "steak-deals-las-vegas", h1: "Steak Specials & Cheap Steak Deals in Las Vegas", title: "Cheap Steak Deals in Las Vegas — Specials & Prime Rib", intro: "Steak specials, prime rib deals and happy-hour steaks across Las Vegas.", where: "(sp.summary ILIKE '%steak%' OR sp.summary ILIKE '%prime rib%' OR v.cuisine ILIKE '%steak%')" },
  { slug: "rooftop-and-patio-happy-hours-las-vegas", h1: "Rooftop & Patio Happy Hours in Las Vegas", title: "Rooftop & Patio Happy Hours in Las Vegas", intro: "Happy hours with a view — rooftops and patios across the Strip and beyond.", where: "(v.vibe_tags::text ILIKE '%rooftop%' OR v.vibe_tags::text ILIKE '%patio%' OR v.vibe_tags::text ILIKE '%view%')" },
  { slug: "dive-bar-happy-hours-las-vegas", h1: "Dive Bar Happy Hours in Las Vegas", title: "Dive Bar Happy Hours in Las Vegas", intro: "Cheap, no-frills dive bar deals where the locals actually drink.", where: "v.vibe_tags::text ILIKE '%dive%'" },
  { slug: "pool-and-dayclub-deals-las-vegas", h1: "Pool & Dayclub Deals in Las Vegas", title: "Las Vegas Pool Party & Dayclub Deals", intro: "Pool and dayclub specials — ladies-free days, cabana and bottle deals, locals offers. Seasonal (spring–fall).", where: "sp.category='pool'" },
  { slug: "gay-bars-las-vegas", h1: "Gay Bars & LGBTQ+ Happy Hours in Las Vegas", title: "Gay Bars & LGBTQ+ Happy Hours in Las Vegas (Fruit Loop & Beyond)", intro: "LGBTQ+ bars and happy hours across Las Vegas, including the Fruit Loop district — verified deals, times and prices.", where: "(v.vibe_tags::text ILIKE '%lgbtq%' OR v.vibe_tags::text ILIKE '%gay%' OR v.name ILIKE '%piranha%' OR v.name ILIKE '%freezone%')" },
  { slug: "sports-bars-las-vegas", h1: "Sports Bar Happy Hours in Las Vegas", title: "Best Sports Bar Happy Hours in Las Vegas", intro: "Game-day deals at Las Vegas sports bars — wells, beer buckets and wing specials, verified and dated.", where: "(v.vibe_tags::text ILIKE '%sports bar%' OR v.name ILIKE '%sports%')" },
  { slug: "cocktail-bars-las-vegas", h1: "Craft Cocktail Bar Happy Hours in Las Vegas", title: "Best Craft Cocktail Bars & Happy Hours in Las Vegas", intro: "Discounted craft cocktails at the city's best bars — verified prices and pour times.", where: "(v.vibe_tags::text ILIKE '%cocktail%' OR v.name ILIKE '%cocktail%')" },
  { slug: "wine-bars-las-vegas", h1: "Wine Bar Happy Hours in Las Vegas", title: "Best Wine Bar Happy Hours in Las Vegas", intro: "Half-price bottles and by-the-glass deals at Las Vegas wine bars.", where: "(v.vibe_tags::text ILIKE '%wine bar%' OR v.name ILIKE '%wine%')" },
  { slug: "breweries-and-beer-bars-las-vegas", h1: "Brewery & Beer Bar Deals in Las Vegas", title: "Las Vegas Brewery Tours, Taprooms & Beer Deals", intro: "Local breweries, taprooms and beer bars with happy hours and pint specials.", where: "(v.vibe_tags::text ILIKE '%brewery%' OR v.vibe_tags::text ILIKE '%beer bar%' OR v.name ILIKE '%brew%' OR v.cuisine ILIKE '%brew%')" },
  { slug: "tiki-bars-las-vegas", h1: "Tiki Bar Happy Hours in Las Vegas", title: "Best Tiki Bars & Mai Tai Deals in Las Vegas", intro: "Frozen drinks, mai tais and tropical happy hours at Las Vegas tiki bars.", where: "(v.vibe_tags::text ILIKE '%tiki%' OR v.name ILIKE '%tiki%')" },
  { slug: "whiskey-bars-las-vegas", h1: "Whiskey & Bourbon Bars in Las Vegas", title: "Best Whiskey Bars & Bourbon Deals in Las Vegas", intro: "Where to find whiskey flights and pour deals across Las Vegas.", where: "(v.vibe_tags::text ILIKE '%whiskey%' OR v.name ILIKE '%whiskey%' OR v.name ILIKE '%whisky%')" },
  { slug: "tequila-and-mezcal-bars-las-vegas", h1: "Tequila & Mezcal Bars in Las Vegas", title: "Tequila & Mezcal Bar Deals in Las Vegas", intro: "Agave-forward happy hours — margarita and mezcal specials citywide.", where: "(v.vibe_tags::text ILIKE '%tequila%' OR sp.summary ILIKE '%mezcal%' OR sp.summary ILIKE '%tequila%' OR sp.summary ILIKE '%margarita%')" },
  { slug: "speakeasy-happy-hours-las-vegas", h1: "Speakeasy & Hidden Bar Happy Hours in Las Vegas", title: "Best Speakeasies & Hidden Bars in Las Vegas", intro: "Tucked-away bars and speakeasies with real happy hours — if you can find the door.", where: "v.vibe_tags::text ILIKE '%speakeasy%'" },
  { slug: "lounge-happy-hours-las-vegas", h1: "Lounge Happy Hours in Las Vegas", title: "Best Lounge Happy Hours in Las Vegas", intro: "Laid-back lounges with discounted drinks and bites across the Strip and off-Strip.", where: "v.vibe_tags::text ILIKE '%lounge%'" },
  { slug: "piano-bars-las-vegas", h1: "Piano Bars & Dueling Pianos in Las Vegas", title: "Best Piano Bars & Dueling Pianos in Las Vegas", intro: "Sing-along piano bars and dueling-piano shows with drink specials.", where: "(v.vibe_tags::text ILIKE '%piano%' OR v.name ILIKE '%piano%')" },
  { slug: "karaoke-bars-las-vegas", h1: "Karaoke Bars in Las Vegas", title: "Best Karaoke Bars & Deals in Las Vegas", intro: "Where to grab the mic — karaoke bars with happy hours and drink deals.", where: "(v.vibe_tags::text ILIKE '%karaoke%' OR v.name ILIKE '%karaoke%')" },
  { slug: "irish-pubs-las-vegas", h1: "Irish Pubs & Pub Happy Hours in Las Vegas", title: "Best Irish Pubs & Pub Deals in Las Vegas", intro: "Pints, pub grub and happy hours at Las Vegas Irish and British pubs.", where: "(v.vibe_tags::text ILIKE '%irish%' OR v.name ILIKE '%irish%' OR v.name ILIKE '% pub%')" },
  { slug: "gastropubs-las-vegas", h1: "Gastropub Happy Hours in Las Vegas", title: "Best Gastropub Happy Hours in Las Vegas", intro: "Elevated pub food and craft beer deals at Las Vegas gastropubs.", where: "(v.vibe_tags::text ILIKE '%gastropub%')" },
  { slug: "hookah-lounges-las-vegas", h1: "Hookah Lounges in Las Vegas", title: "Best Hookah Lounges & Deals in Las Vegas", intro: "Late-night hookah lounges with drink specials across Las Vegas.", where: "(v.vibe_tags::text ILIKE '%hookah%' OR v.name ILIKE '%hookah%')" },
  { slug: "cigar-lounges-las-vegas", h1: "Cigar Lounges in Las Vegas", title: "Best Cigar Lounges & Bars in Las Vegas", intro: "Cigar-friendly lounges and bars with happy hours in Las Vegas.", where: "(v.vibe_tags::text ILIKE '%cigar%' OR v.name ILIKE '%cigar%')" },
  { slug: "country-bars-las-vegas", h1: "Country Bars & Honky-Tonks in Las Vegas", title: "Best Country Bars & Line Dancing in Las Vegas", intro: "Line dancing, mechanical bulls and drink deals at Las Vegas country bars.", where: "(v.vibe_tags::text ILIKE '%country%' OR v.name ILIKE '%honky%' OR v.name ILIKE '%stoney%' OR v.name ILIKE '%gilley%')" },
  { slug: "date-night-happy-hours-las-vegas", h1: "Date-Night Happy Hours in Las Vegas", title: "Best Date-Night Happy Hours in Las Vegas", intro: "Romantic bars and restaurants with happy hours perfect for a date.", where: "v.vibe_tags::text ILIKE '%date night%'" },
  { slug: "upscale-happy-hours-las-vegas", h1: "Upscale Happy Hours in Las Vegas", title: "Best Upscale & Luxury Happy Hours in Las Vegas", intro: "High-end happy hours — discounted bubbles, caviar and craft cocktails at Vegas's nicest rooms.", where: "v.vibe_tags::text ILIKE '%upscale%'" },
  { slug: "hidden-gem-happy-hours-las-vegas", h1: "Hidden-Gem Happy Hours in Las Vegas", title: "Hidden-Gem Happy Hours Locals Love in Las Vegas", intro: "Under-the-radar happy hours the tourists miss — verified by locals.", where: "v.vibe_tags::text ILIKE '%hidden gem%'" },
  { slug: "gaming-bar-happy-hours-las-vegas", h1: "Gaming Bar Happy Hours in Las Vegas", title: "Best Bar-Top Gaming Happy Hours in Las Vegas", intro: "Bar-top video poker spots with free or cheap drinks while you play.", where: "v.vibe_tags::text ILIKE '%gaming%'" },
  { slug: "live-music-happy-hours-las-vegas", h1: "Live Music Happy Hours in Las Vegas", title: "Best Live Music Bars & Happy Hours in Las Vegas", intro: "Catch live music with your happy hour — verified bars with bands and DJs.", where: "v.vibe_tags::text ILIKE '%live music%'" },
  { slug: "24-hour-bars-las-vegas", h1: "24-Hour Bars & All-Day Happy Hours in Las Vegas", title: "24-Hour Bars & All-Day Drink Deals in Las Vegas", intro: "Vegas never closes — bars with round-the-clock or all-day drink specials.", where: "(v.vibe_tags::text ILIKE '%24-hour%' OR v.vibe_tags::text ILIKE '%24 hour%' OR sp.start_time ILIKE '%all day%')" },
  { slug: "mexican-happy-hours-las-vegas", h1: "Mexican Happy Hours in Las Vegas", title: "Best Mexican Happy Hours & Margarita Deals in Las Vegas", intro: "Taco and margarita happy hours at Las Vegas Mexican restaurants and cantinas.", where: "(v.cuisine ILIKE '%mexican%' OR sp.summary ILIKE '%taco%' OR sp.summary ILIKE '%margarita%')" },
  { slug: "italian-happy-hours-las-vegas", h1: "Italian Happy Hours in Las Vegas", title: "Best Italian Happy Hours in Las Vegas", intro: "Discounted pasta, wine and aperitivo deals at Las Vegas Italian spots.", where: "(v.cuisine ILIKE '%italian%' OR sp.summary ILIKE '%pasta%' OR sp.summary ILIKE '%aperiti%')" },
  { slug: "thai-happy-hours-las-vegas", h1: "Thai Happy Hours in Las Vegas", title: "Best Thai Happy Hours in Las Vegas", intro: "Thai restaurants with happy hours — discounted bites and drinks citywide.", where: "v.cuisine ILIKE '%thai%'" },
  { slug: "french-happy-hours-las-vegas", h1: "French Happy Hours in Las Vegas", title: "Best French Happy Hours & Wine Deals in Las Vegas", intro: "French bistros and brasseries with happy hours — wine and bubbles deals.", where: "v.cuisine ILIKE '%french%'" },
  { slug: "bbq-happy-hours-las-vegas", h1: "BBQ Happy Hours & Deals in Las Vegas", title: "Best BBQ Happy Hours & Deals in Las Vegas", intro: "Smoked meats and beer deals at Las Vegas barbecue joints.", where: "(v.cuisine ILIKE '%bbq%' OR v.cuisine ILIKE '%barbe%' OR sp.summary ILIKE '%bbq%' OR sp.summary ILIKE '%brisket%')" },
  { slug: "pizza-happy-hours-las-vegas", h1: "Pizza Happy Hours & Slice Deals in Las Vegas", title: "Best Pizza Happy Hours & Slice Deals in Las Vegas", intro: "Slice deals and pizza-and-pint happy hours across Las Vegas.", where: "(sp.summary ILIKE '%pizza%' OR sp.summary ILIKE '%slice%' OR v.cuisine ILIKE '%pizz%')" },
  { slug: "burger-happy-hours-las-vegas", h1: "Burger Happy Hours & Deals in Las Vegas", title: "Best Burger Happy Hours & Deals in Las Vegas", intro: "Burger-and-beer specials and happy-hour sliders citywide.", where: "(sp.summary ILIKE '%burger%' OR sp.summary ILIKE '%slider%')" },
  { slug: "all-day-happy-hours-las-vegas", h1: "All-Day Happy Hours in Las Vegas", title: "All-Day Happy Hours in Las Vegas", intro: "Bars where happy hour runs all day — verified open-to-close drink deals.", where: "sp.start_time ILIKE '%all day%'" },
  { slug: "daily-happy-hours-las-vegas", h1: "Daily (7-Day) Happy Hours in Las Vegas", title: "Daily Happy Hours in Las Vegas — 7 Days a Week", intro: "Happy hours that run every day, weekends included — verified and dated.", where: "(sp.days ILIKE '%daily%' OR sp.days ILIKE '%every%' OR sp.days ILIKE '%7 day%')" },
  { slug: "weekend-happy-hours-las-vegas", h1: "Weekend Happy Hours in Las Vegas", title: "Best Weekend Happy Hours in Las Vegas (Sat & Sun)", intro: "Saturday and Sunday happy hours — the deals that survive the weekend.", where: "(sp.days ILIKE '%sat%' OR sp.days ILIKE '%sun%' OR sp.days ILIKE '%daily%' OR sp.days ILIKE '%weekend%')" },
  { slug: "cheapest-beer-las-vegas-strip", h1: "Cheapest Beer on the Las Vegas Strip", title: "Cheapest Beer on the Las Vegas Strip", intro: "The lowest beer prices on the Strip right now — drafts, pints and buckets, verified.", where: "(sp.drink AND (sp.summary ILIKE '%beer%' OR sp.summary ILIKE '%draft%' OR sp.summary ILIKE '%pint%' OR sp.summary ILIKE '%bucket%') AND v.neighborhood ILIKE '%strip%')" },
  { slug: "dollar-oysters-las-vegas", h1: "$1 Oyster Deals in Las Vegas", title: "$1 Oysters & Dollar Oyster Happy Hours in Las Vegas", intro: "Where to find dollar oysters in Las Vegas right now — verified prices and times.", where: "(sp.summary ILIKE '%oyster%' AND (sp.summary ILIKE '%$1%' OR sp.summary ILIKE '%dollar%' OR sp.price = 1))" },
  { slug: "taco-tuesday-las-vegas", h1: "Taco Tuesday Deals in Las Vegas", title: "Best Taco Tuesday Deals in Las Vegas", intro: "Dollar tacos, taco-and-margarita specials and Taco Tuesday deals across Las Vegas — verified and dated.", where: "((sp.summary ILIKE '%taco%' AND (sp.days ILIKE '%tue%' OR sp.days ILIKE '%daily%')) OR sp.summary ILIKE '%taco tuesday%')" },
  { slug: "wine-wednesday-las-vegas", h1: "Wine Wednesday Deals in Las Vegas", title: "Best Wine Wednesday Deals in Las Vegas", intro: "Half-price bottles and by-the-glass Wine Wednesday specials across Las Vegas.", where: "((sp.summary ILIKE '%wine%' AND sp.days ILIKE '%wed%') OR sp.summary ILIKE '%wine wednesday%')" },
  { slug: "ladies-night-las-vegas", h1: "Ladies Night Deals in Las Vegas", title: "Best Ladies Night Deals & Free Drinks in Las Vegas", intro: "Ladies-free entry, free and discounted drinks — every verified Ladies Night in Las Vegas.", where: "(sp.summary ILIKE '%ladies night%' OR sp.summary ILIKE '%ladies free%' OR sp.summary ILIKE '%ladies drink%')" },
  { slug: "industry-night-las-vegas", h1: "Service Industry Night (SIN) Deals in Las Vegas", title: "Best Service Industry Night Deals in Las Vegas", intro: "Where Vegas hospitality workers drink — SIN / industry-night specials, verified and dated.", where: "(sp.summary ILIKE '%industry night%' OR sp.summary ILIKE '%service industry%' OR sp.summary ILIKE '% sin %' OR sp.fine_print ILIKE '%industry%')" },
  { slug: "brunch-deals-las-vegas", h1: "Brunch Deals & Bottomless Mimosas in Las Vegas", title: "Best Brunch Deals & Bottomless Mimosas in Las Vegas", intro: "Bottomless mimosas, boozy brunch and weekend brunch specials across Las Vegas.", where: "(sp.summary ILIKE '%brunch%' OR sp.summary ILIKE '%bottomless%' OR sp.summary ILIKE '%mimosa%')" },
];

export function getLanding(slug: string) { return LANDINGS.find((l) => l.slug === slug) || null; }

export async function landingResults(def: Landing): Promise<any[]> {
  const p = gp(); if (!p) return [];
  try {
    const { rows } = await p.query(`
      SELECT v.id, v.name, v.neighborhood, v.rating, v.photo_ref,
        MIN(sp.price) FILTER (WHERE sp.price IS NOT NULL) AS cheapest, COUNT(sp.id) AS deal_count,
        json_agg(json_build_object('summary', sp.summary, 'price', sp.price, 'days', sp.days, 'start', sp.start_time, 'end', sp.end_time, 'outlet', sp.outlet) ORDER BY sp.confidence DESC) AS specials
      FROM specials sp JOIN venues v ON v.id = sp.venue_id
      WHERE sp.status='live' AND (sp.valid_until IS NULL OR sp.valid_until >= CURRENT_DATE) AND (${def.where})
      GROUP BY v.id
      ORDER BY (v.rating IS NULL), v.rating DESC NULLS LAST
      LIMIT 60`);
    return rows;
  } catch (e) { return []; }
}
